### ISSUE TITLE
name clash with existing npm module

### ISSUE THREAD

**Issue by aaronhaines** [sammyt/nap#10]
Unfortunately there is an existing npm module called nap.
If we ever want to make nap available through npm we will have to rename the project.

**Comment by mstade** [comment]
Pretty much any name is taken in npm these days. It's also not surprising that `nap` in node is a packager/compiler/whatever-everyone-else-has-done-219381273987123-times-already-but-different-syntax-yay! project either. Not having a user/organization scheme like GitHub is really a bummer, and one of the reasons we wrote dave in the first place. That and the whole CouchDB madness of npm.

Anyway, what with npm receiving VC and becoming a separate company and all, maybe it's worth waiting for a while to see what happens?

**Comment by sammyt** [comment]
> maybe it's worth waiting 

I'm good at waiting

**Comment by mstade** [comment]
Alright fellas, this is now in the cards again, as I'm actively looking at pushing to npm at the moment. Since this issue was created, npm has indeed added [organization support](https://docs.npmjs.com/getting-started/working-with-orgs) – should we perhaps get us one of those?

The other option, as I see it, is to just rename the project. @aaronhaines you know better than I do what kind of internal repercussions this would have.

**Comment by mstade** [comment]
Hmm, there's also something they call "scopes" which is probably more to the point, however they are related. [More info in the docs](https://docs.npmjs.com/getting-started/scoped-packages). Anyway, we oughta scope the package, unless we rename it. What do you guys think?

**Comment by aaronhaines** [comment]
We use scopes to avoid name clashes between packages in our internal registry and public npm. Organisations seems to just be managing who can publish under a particular scope, unless I am misunderstanding it.

**Comment by aaronhaines** [comment]
It wouldn't cause us a huge amount of pain to rename it, but I think adding a scope is the better option

**Comment by mstade** [comment]
Is renaming and adding a scope not the same thing, technically? The scope does have the benefit of the ability to have an org around it, which is perhaps a good thing so that the rights to publish can be shared?

**Comment by mstade** [comment]
Looks like it's possible to grant publish rights to individual packages; so it wouldn't matter much in terms of the ability for multiple people to publish, if things get published under a user scope or some arbitrary scope tied to an organization. Although the latter does seem like a good choice. Any thoughts @sammyt?

**Comment by aaronhaines** [comment]
Yes, you're right. Technically we would still have to update references to the lib to include the scope, but it wouldn't be to hard to do.

**Comment by mstade** [comment]
Alright, cool. So it just comes down to picking a poison then. I don't have strong feelings either way. I like the name nap, particularly the etymology as explained by @sammyt, but it's just a name. The scope (and particularly in conjunction with an org) route affords us the ability to group things, should that be desirable.

**Comment by mstade** [comment]
Scope name suggestion: `websdk`. It's in line with our history, it's to the point, and we own the [organization](https://github.com/websdk). Feel free to start coming up with other suggestions!

**Comment by mstade** [comment]
This issue was moved to websdk/nap#3
