### ISSUE TITLE
remove browser dependence from core

### ISSUE THREAD

**Issue by sammyt** [sammyt/nap#13]
want core of nap to work in nodejs, do need to isolate the parts the have a browser dependency

**Comment by mstade** [comment]
I can do this. Is it presumptious of me then to also split things into modules and adding browserify as a build step? I'm thinking that we then also put this in npm. I'll contact the [other nap guy](https://www.npmjs.org/package/nap) and ask whether he'd be ok with releasing the name.

**Comment by mstade** [comment]
Merge this with #14 actually?

**Comment by sammyt** [comment]
> I can do this

that would be awesome

**Comment by mstade** [comment]
I want to push my changes, but I'm not a collaborator. :o(

Do you want to make me one, or should I fork and PR back? Also applied to rhumb btw.

**Comment by sammyt** [comment]
I will make you a collaborator when I'm back at my laptop.

## Marvellous work Sir.

-----Original Message-----

**Comment by mstade** [comment]
Right on. I need it for rhumb too, since it too needed restructuring. I'll open up PRs for both, but I reckon they shouldn't be merged right away but rather I'd like to split things up into smaller modules first. Once I open the PR we can close this and #14.

**Comment by haggyj** [comment]
This makes me happy.

**Comment by mstade** [comment]
@haggyj :o)

We're starting work to really evolve nap into something pretty cool. It will move fast and break a lot along the way, so if you guys are using it you may want to fork or stay at a certain commit until the dust settles a bit. Of course, we should also all meet up for lunch/coffee/beer/whatever sometime soon!
