### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by mstade** [sammyt/nap#17]
When you make requests to resources that don't exist in a web, there's currently no information to let you know it was a 404. We should add this, and other things, that make debugging easier.

**Comment by haggyj** [comment]
@aaronhaines did this via middleware in our sugary syntactic wrapper.

**Comment by mstade** [comment]
That's pretty sweet dude. Should probably be part of nap though, we should be friendlier. We were also talking today about potentially hooking into the network tab to log requests. Would be nifty.

**Comment by haggyj** [comment]
:+1:

**Comment by aaronhaines** [comment]
We have a couple of default middlewares we use - for logging and for
handling request timeouts.

We could just bundle those with nap.

**Comment by aaronhaines** [comment]
Actually there is an example in examples/middleware.html

**Comment by mstade** [comment]
This issue was moved to websdk/nap#6
