### ISSUE TITLE
return view functions from resources

### ISSUE THREAD

**Issue by aaronhaines** [sammyt/nap#9]
I have a version of this working as per this gist: https://gist.github.com/aaronhaines/8934810

also a example of how the config would look: https://gist.github.com/aaronhaines/8934892

Have a look at the changes on my fork here: https://github.com/aaronhaines/nap

I'm creating a response object and passing it though as the scope to the various handlers. Probably need a better solution for preventing the response scope from being exposed to the resource function.

Selector negotiation is now a standalone function which can be optionally used by views and could be moved out of the core library along with the 'into' client. nap itself doesn't need to have any dom handling code at all.

**Comment by mstade** [comment]
This issue was moved to websdk/nap#2
